config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  # relationships
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  # validations
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  # relationships
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  # relationships
  has_many :article_categories
  has_many :articles, through: :article_categories
  # validations
  validates :name, presence: true, length: {minimum: 4, maximum: 25}
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  # relationships
  has_many :articles, dependent: :destroy
  # before saving field
  before_save { self.email = email.downcase }
  # validations
  validates :username,  presence: true, 
                        uniqueness: { case_sensitive: false }, 
                        length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                    uniqueness: { case_sensitive: false }, 
                    length: { maximum: 150 }, 
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "log in to perform that action"
      redirect_to login_path
    end
  end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]


  # show list of articles
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end
  # show individual article
  def show
  end
  # show form for new article
  def new
    @article = Article.new
    @categories = Category.all
  end
  # edit an article
  def edit
  end
  # create a new article in db
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "article created successfully"
      redirect_to @article
    else
      render 'new'
    end
  end
  
  # update the article in db
  def update
    if @article.update(article_params)
      flash[:notice] = "article updated successfully"
      redirect_to @article
    else
      render 'edit'
    end
  end

  # destroy the article in db
  def destroy
    @article.destroy
    flash[:notice] = "article deleted successfully"
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "you can only edit your own article"
      redirect_to @article
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def new
    @category = Category.new
  end


  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "category was successfully edited"
      redirect_to @category
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "category updated successfully"
      redirect_to @category
    else
      render 'edit'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "only admins can perform that action"
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
      redirect_to articles_path if logged_in?
    end
    def about
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
def new
end

def create
  user = User.find_by(email: params[:session][:email].downcase)
  if user && user.authenticate(params[:session][:password])
    session[:user_id] = user.id
    flash[:notice] = "logged in successfully"
    redirect_to user
  else
    flash.now[:alert] = "incorrect username and/or password"
    render 'new'
  end
end

def destroy
  session[:user_id] = nil
  flash[:notice] = "logged out successfully"
  redirect_to root_path
end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def new
    @user = User.new
  end

  # show list of users
  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end
  
  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def edit
  end

   # update the article in db
  def update
    if @user.update(user_params)
      flash[:notice] = "User settings updated successfully"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "welcome, #{@user.username}, you have successfully signed in"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def destroy
    @user.destroy
    if current_user == @user
      session[:user_id] = nil
      redirect_to root_path
    else
      redirect_to users_path
    end
    flash[:notice] = "user deleted successfully"

  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "you can only edit your own settings"
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end


end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
  <%@articles.each do | article | %>
    <div class="row justify-content-center">
      <div class="col-8">
        <div class="card text-center mt-4">
          <h5 class="card-header fst-italic fw-lighter">by <%= link_to article.user.username, user_path(article.user), class: "text-success text-decoration-none" if article.user %></h5>
          <div class="mt-2">
            <% if article.categories.any? %>
              <%= render article.categories %>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= article.description %></p>
            <button class="btn btn-outline-success"><%= link_to 'Show', article_path(article), class: "text-success text-decoration-none" %></button>
            <% if logged_in? && (current_user == article.user || current_user.admin?) %>
              <button class="btn btn-outline-info"><%= link_to 'Edit', edit_article_path(article), class: "text-info text-decoration-none"%></button>
              <button class="btn btn-outline-danger"> <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: "Are you sure?" }, class: "text-danger text-decoration-none" %></button>
            <% end %>
          </div>
          <div class="card-footer">
            <small class="text-muted">created <%= time_ago_in_words(article.created_at) %> ago</small><br>
            <hr class="sep"/>
            <small class="text-muted">edited <%= time_ago_in_words(article.updated_at) if article.updated_at %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @article %>
      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-white rounded",local: true) do |f| %>
        <div class="form-group row mb-3">
          <%= f.label :title, "title", class:"col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_field :title, class:"form-control shadow rounded", placeholder: "enter the title of the article"%>
          </div>
        </div>
        <div class="form-group row mb-3">
          <%= f.label :description, "description",  class:"col-2 col-form-label"%>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class:"form-control shadow rounded", placeholder: "enter a description of the article" %>
          </div>
        </div>
        <div class="form-group row mb-3">
          <%= f.label :category, "categories", class:"col-2 col-form-label"%>
          <div class="col-10">
            <%= f.collection_select(:category_ids, Category.all, :id, :name, { prompt: "choose categories from below (can stay empty)" }, { multiple: true, class: "form-select shadow rounded" })%>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <%= f.submit "save", class:"btn btn-outline-success btn-lg w-25 col-10" %>
        </div>
      <% end %>
      <div class="text-center">
        <%= link_to 'cancel and return to articles', articles_path, class:"text-light text-decoration-none"%>
      </div>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
  
<h1 class="text-center mt-4">edit article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">articles</h1>
<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>
<%= render 'article' %>
<div class="flickr_pagination mt-3">
  <%= will_paginate @users, :container => false %>
  <div class="page_info">
    <%= page_entries_info @articles %>
  </div>
</div>

app/views/articles/new.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">create a new article</h1>
  <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div class="container">
  <h1 class="text-center"><%= @article.title %></h5>
  <div class="row justify-content-center">
    <div class="col-8">
      <div class="card text-center mt-4 shadow mb-5 bg-white rounded">
        <div class="card-header fst-italic fw-lighter">
          <div class="d-flex justify-content-center">
            <div class="mx-2">by <%= link_to @article.user.username, user_path(@article.user) if @article.user %></div>
            <%= link_to gravatar_for(@article.user, size: 25), user_path(@article.user) %>
          </div>
          <div class="mt-2">
            <% if @article.categories.any? %>
              <%= render @article.categories %>
            <% end %>
          </div>
        </div>
        <div class="card-body">
          <div class="card-text text-start"><%= simple_format(@article.description) %></div>
          <% if logged_in? && (current_user == @article.user || current_user.admin?)%>
            <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-info"%>
            <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
          <% end %>
        </div>
        <div class="card-footer">
          <small class="text-muted">created <%= time_ago_in_words(@article.created_at) %> ago</small><br>
          <hr class="sep"/>
          <small class="text-muted">edited <%= time_ago_in_words(@article.updated_at) if @article.updated_at %> ago</small>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge rounded-pill bg-info text-decoration-none" %>

app/views/categories/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @category %>
      <%= form_with(model: @category, local: true, class: "shadow p-3 mb-3 bg-white rounded") do |f| %>
        <div class="form-group row mb-3">
          <%= f.label :name, "name", class:"col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_field :name, placeholder: "enter a new category name", class:"form-control shadow rounded"%>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <%= f.submit class:"btn btn-outline-success btn-lg w-25" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">edit category</h1>
<%= render 'form' %>
<div class="text-center">
  <%= link_to 'cancel and return to category', category_path(@category), class:"text-light text-decoration-none"%>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">categories</h1>
<div class="flickr_pagination">
  <%= will_paginate @categories, :container => false %>
</div>
<div class="container">
  <%@categories.each do | category | %>
    <div class="row justify-content-center">
      <div class="col-4">
        <div class="card text-center mt-4">
          <div class="card-body">
            <div class="card-title">
              <%= link_to category.name.downcase, category_path(category), class: "text-success text-decoration-none"%>
            </div>
            <div class="card-text">
              <%= pluralize(category.articles.count, "article")%>
            </div>
          </div>
          <div class="card-footer">
            <small class="text-muted">created <%= time_ago_in_words(category.created_at) %> ago</small><br>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="flickr_pagination mt-3">
    <%= will_paginate @categories, :container => false %>
    <div class="page_info">
      <%= page_entries_info @categories %>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">add new category</h1>
<%= render 'form' %>
<div class="text-center">
  <%= link_to 'cancel and return to categories', categories_path, class:"text-light text-decoration-none"%>
</div>

app/views/categories/show.html.erb
<div class="container">
  <h1 class="text-center mt-4">category: <%= @category.name.downcase %></h1>
  <% if logged_in? && current_user.admin?%>
    <div class="text-center mt-4">
      <%= link_to "edit category", edit_category_path(@category), class: "btn btn-outline-info" %>
    </div>
  <% end %>
  <h3 class="text-center mt-4">articles</h3>
  <%= render 'articles/article'%>
  <div class="flickr_pagination mt-3">
    <%= will_paginate @articles, :container => false %>
    <div class="page_info">
      <%= page_entries_info @articles %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white-50 mt-4">
  <div class="container text-center">
    <small>Copyright &copy; rebecca rossman</small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "alert" ? "danger" : "success" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "betablog", root_path, class:"navbar-brand", id:"logo"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'bloggers', users_path, class:"nav-link"%>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            articles
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'view articles', articles_path, class:"dropdown-item"%>
            <%= link_to 'view categories', categories_path, class:"dropdown-item"%>
            <% if logged_in? %>
              <%= link_to 'create new article', new_article_path, class:"dropdown-item"%>
              <% if current_user.admin %>
                <%= link_to 'create new category', new_category_path, class:"dropdown-item"%>
              <% end %>
            <% end %>
          </ul>
        </li>
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= "admin" if current_user.admin? %>
              <%= current_user.username if current_user %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "profile", user_path(current_user), class:"dropdown-item"%>
              <%= link_to 'settings', edit_user_path(current_user), class: "dropdown-item"%>
              <%= link_to 'logout', logout_path, class:"dropdown-item", method: :delete%>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'log in', login_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'sign up', signup_path, class:"nav-link"%>
          </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>betablog</title>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the About page</h1>

<td><%= link_to 'Articles', articles_path%></td>
<td><%= link_to 'Home', root_path%></td>

app/views/pages/home.html.erb
<div class="p-5 rounded-3">
  <div class="container-fluid py-5 jumbotron text-center">
    <h1 class="display-4 fw-bold" id="home-title">betablog</h1>
    <div class="mt-4">
      <%= link_to 'sign up', signup_path, class:"btn btn-success btn-lg"%>
      <%= link_to 'log in', login_path, class:"btn btn-success btn-lg"%>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<div class="container">
  <% if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <h3 class="alert-heading text-center">please fix the following errors</h3>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      <ul>
        <% obj.errors.full_messages.each do |error| %>
          <li> <%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, local: true, class: "shadow p-3 mb-3 bg-white rounded") do |f| %>
        <div class="form-group row mb-3">
          <%= f.label "username", :username, class:"col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_field :username, placeholder: "enter a username", class:"form-control shadow rounded"%>
          </div>
        </div>
        <div class="form-group row mb-3">
          <%= f.label "email", :email, class:"col-2 col-form-label"%>
          <div class="col-10">
            <%= f.email_field :email, class:"form-control shadow rounded", placeholder: "enter a valid email address" %>
          </div>
        </div>
        <div class="form-group row mb-3">
          <%= f.label "password", :password, class:"col-2 col-form-label"%>
          <div class="col-10">
            <%= f.password_field :password, class:"form-control shadow rounded", placeholder: "enter a password" %>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <%= f.submit(@user.new_record? ? "sign up" : "update", class:"btn btn-outline-success btn-lg w-25") %>
        </div>
        <% if logged_in? && current_user == @user %>
          <div class="form-group row justify-content-center">
            <%= link_to 'delete account', user_path(@user), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger w-25 mt-3" %>
          </div>
        <% end %>
      <% end %>
      <% if logged_in? %>
        <div class="text-center">
          <%= link_to 'cancel and return to articles', articles_path, class:"text-light text-decoration-none"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">edit settings</h1>
  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<h1 class="text-center mt-4">betabloggers</h1>
<div class="flickr_pagination">
  <%= will_paginate @users, :container => false %>
</div>
<div class="container">
  <%@users.each do | user | %>
    <div class="row justify-content-center">
      <div class="col-8">
        <div class="card text-center mt-4">
          <h5 class="card-header fst-italic fw-lighter"><%= link_to user.username, user, class: "text-success text-decoration-none"%></h5>
          <div class="card-body">
            <%= link_to gravatar_for(user, size: 150), user %>
            <p class="card-text mt-3"><%= pluralize(user.articles.count, "article") %></p>
            <%= link_to 'view profile', user, class: "btn btn-outline-success" %>
            <% if logged_in? %>
              <% if current_user == user %>
                <%= link_to 'edit profile', edit_user_path(user), class: "btn btn-outline-info"%>
              <% end %>
              <% if  current_user.admin? %>
                <%= link_to 'delete user', user_path(user), class: "btn btn-outline-danger", method: :delete, data: {confirm: "are you sure you want to delete this user account?"} %>
              <% end %>
            <% end %>
          </div>
          <div class="card-footer">
            <small class="text-muted">joined <%= time_ago_in_words(user.created_at) %> ago</small><br>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="flickr_pagination mt-3">
    <%= will_paginate @users, :container => false %>
    <div class="page_info">
      <%= page_entries_info @users %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">sign up</h1>
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>
  <%= gravatar_for(@user, size: 200) %>
  <% if logged_in? && current_user == @user%>
    <div class="text-center mt-4"><%= link_to "edit profile", edit_user_path(@user), class: "btn btn-outline-info" %></div>
  <% end %>
  <h3 class="text-center mt-4">articles</h3>
  <%= render 'articles/article'%>
  <div class="flickr_pagination mt-3">
    <%= will_paginate @articles, :container => false %>
    <div class="page_info">
      <%= page_entries_info @articles %>
    </div>
  </div>
</div>